spring:
  datasource:
    url: jdbc:mysql://xxxx:3306/xxx?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8
    username: xxxx
    password: xxxx
    driver-class-name: com.mysql.cj.jdbc.Driver
